// coins
export const UPDATE_COIN_AMOUNT = 'UPDATE_COIN_AMOUNT';

// user
export const FETCH_USER_INFO = 'FETCH_USER_INFO';

// products
export const FETCH_PRODUCTS_CATALOG = 'FETCH_PRODUCTS_CATALOG';
export const CHANGE_PRODUCTS_CATALOG_PAGE = 'CHANGE_PRODUCTS_CATALOG_PAGE';
export const CHANGE_PRODUCTS_SORT_OPTION = 'CHANGE_PRODUCTS_SORT_OPTION';