// coins
export const UPDATE_COIN_AMOUNT = 'UPDATE_COIN_AMOUNT';

// user
export const FETCH_USER_INFO = 'FETCH_USER_INFO';

// products
export const FETCH_PRODUCTS_CATALOG = 'FETCH_PRODUCTS_CATALOG';
export const CHANGE_PRODUCTS_CATALOG_PAGE = 'CHANGE_PRODUCTS_CATALOG_PAGE';
export const CHANGE_PRODUCTS_SORT_OPTION = 'CHANGE_PRODUCTS_SORT_OPTION';

// purchase
export const REDEEM_PRODUCT = 'REDEEM_PRODUCT';

// messages
export const HIDE_SUCCESS_REDEEM_MESSAGE = 'HIDE_SUCCESS_REDEEM_MESSAGE';

//theme
export const CHANGE_CURRENT_THEME = 'CHANGE_CURRENT_THEME';
